### ISSUE TITLE
TousAntiCovid static API version bump

### ISSUE THREAD

**Issue by liamjack** [rgrunbla/TAC-Files#4]
TousAntiCovid's static API version has been bumped to `36`: https://gitlab.inria.fr/stopcovid19/stopcovid-android/-/blob/master/coreui/src/main/java/com/lunabeestudio/stopcovid/coreui/ConfigConstant.kt#L15

Environment variable: `API_VERSION`

**Comment by rgrunbla** [comment]
Thanks :)

But it seems it's still not in production yet, isn't it ?
